# Which Entities drop Food Items that cause Hunger?

SELECT ?entityName ?itemName
WHERE {
    ?entity rdf:type mc:Entity ;
        mc:hasDisplayName ?entityName ;
        mc_entity:hasDrop ?entityLoot . 
    ?entityLoot mc_entity_loot:hasItem ?item .
    ?item a mc:Food ;
        mc:hasDisplayName ?itemName ;
        mc_food:givesEffect ?foodEffect .
    ?foodEffect a mc:FoodEffect ;
        mc_effect:hasEffect ?effect .
    FILTER (?effect = mc_effect:hunger)
}
