# Which Entities drop Food Items that cause Hunger?

SELECT ?itemName (?entityName AS ?droppedBy)
WHERE {
    ?entity rdf:type mc:Entity ;
        mc:hasDisplayName ?entityName ;
        mc_entity:hasDrop ?entityDrop . 
    ?entityDrop mc_entity_drop:hasItem ?item .
    ?item a mc:Food ;
        mc:hasDisplayName ?itemName ;
        mc_item:givesEffect ?foodEffect .
    ?foodEffect a mc:FoodEffect ;
        mc_effect:hasEffect ?effect .
    FILTER (?effect = mc_effect:hunger)
}
