# What can I enchant my helmet with?

SELECT ?displayName ?enchantmentName
WHERE {
    ?item a mc:Item ;
        mc:hasDisplayName ?displayName ;
        mc_item:hasEnchantCategory ?categoryA .
    ?enchantment a mc:Enchantment ;
        mc_enchantment:hasCategory ?categoryB ;
        mc:hasDisplayName ?enchantmentName .
    FILTER (?categoryA = ?categoryB)
    FILTER (?displayName = xsd:string("Iron Helmet"))
}