PREFIX mc: <http://example.org/minecraft/>
PREFIX mc_block: <http://example.org/minecraft/block/>
PREFIX mc_block_drop: <http://example.org/minecraft/block_drop/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?enchantmentName ?excludeName
WHERE {
  ?enchantment rdf:type mc:Enchantment .
  ?enchantment mc:hasName ?enchantmentName .
  ?enchantment mc_enchantment:hasExclude ?exclude .
  ?exclude mc:hasName ?excludeName .
}
